fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: check-yaml
    - id: check-ast
    - id: check-json
    - id: check-added-large-files
    - id: detect-private-key # detects the presence of private keys.
    - id: double-quote-string-fixer
    - id: mixed-line-ending
    - id: requirements-txt-fixer
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: 'v1.7.0'  # Use the sha / tag you want to point at
  hooks:
    - id: autopep8
- repo: https://github.com/asottile/pyupgrade
  rev: v2.37.3
  hooks:
    - id: pyupgrade
      args: [--py36-plus]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v14.0.6
  hooks:
  - id: clang-format
    types_or: [c++, c, cuda]
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1  # pick a git hash / tag to point to
  hooks:
    - id: pydocstyle
      exclude: ^scripts/
